---
title: All I Wanna Buy
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  - scope:
      type: posts
      path: _posts
    values:
      layout: default
description: 'Website description.'
lang: fr
author: Author name
google_analytics:
gems:
- jekyll-feed
- jekyll-paginate-v2
exclude:
- Gemfile
- Gemfile.lock
permalink: "/:categories/:title/"
pagination:
  enabled: true
  per_page: 1
autopages:
  enabled: true
  categories:
    permalink: '/:cat'
  tags:
    permalink: '/:tag'
