---
title: All I Wanna Buy
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  wants:
    title: Wants
    output: true
description: 'Website description.

'
lang: fr
author: Author name
google_analytics: 
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
permalink: "/blog/:title.html"
